### PR TITLE
Spending level filter on layers menu; school/URL index

### PR DESCRIPTION
**Pull request by jgordon510**
1) Only three spending levels for the menu (maybe the dots, too?)
2) Get rid of the old legend
3) Added spending levels that reflect the per student and total spending; change when your view changes

This means that you've lost the size of the bubbles reflecting the overall spending.  If that doesn't seem acceptable to you, then it's probably not worth digging into making the SQL query work with the new filter.

If you commit this, make sure you update index.html to point to your own viz.json file.

screenshot 2015-06-24 at 12 04 08 am

### CODE REVIEW

**Comment by jbaldo** [comment]
Awesome! Interesting idea to get rid of the legend. I'll play around with this over the next few days.

**Comment by jgordon510** [comment]
Oh good. It made sense to me, but I wasn't sure.  I might play with the SQL
query. I think the ranges should update based on the highest and lowest
values currently displayed on the map, because the ranges really change as
you add/remove categories.  That means polling everything that's displayed
for its value, building a range array, and using that array to create the
menu strings for the ranges, as well as constrain the SQL query.

Also, here's an index of the school websites, using OUSD's provided domain
numbers.  I didn't check every one, but I think the school name strings are
coming from the same dataset you're using, so this should work:

http://www.ousd.k12.ca.us/Domain/2348,Adult and Career Education

http://www.ousd.k12.ca.us/Domain/609,Acorn Woodland Elementary

http://www.ousd.k12.ca.us/Domain/206,Allendale Elementary

http://www.ousd.k12.ca.us/Domain/2776,Alliance Academy

http://www.ousd.k12.ca.us/Domain/2020,Architecture Academy

http://www.ousd.k12.ca.us/Domain/761,Ascend Elementary

http://www.ousd.k12.ca.us/Domain/2493,Barack Obama Academy

http://www.ousd.k12.ca.us/Domain/235,Bella Vista Elementary

http://www.ousd.k12.ca.us/Domain/2441,Bret Harte Middle School

http://www.ousd.k12.ca.us/Domain/789,Bridges Academy

http://www.ousd.k12.ca.us/Domain/246,Brookfield Village Elementary

http://www.ousd.k12.ca.us/Domain/1861,Bunche Academy

http://www.ousd.k12.ca.us/Domain/1367,Burbank Center

http://www.ousd.k12.ca.us/Domain/261,Burckhalter Elementary

http://www.ousd.k12.ca.us/Domain/2189,Business Information & Technology HS

http://www.ousd.k12.ca.us/Domain/2252,Business, Entrepreneurial School of
Technology (BE

http://www.ousd.k12.ca.us/Domain/800,Carl B. Munck Elementary

http://www.ousd.k12.ca.us/Domain/2200,Castlemont High School

http://www.ousd.k12.ca.us/Domain/288,Chabot Elementary

http://www.ousd.k12.ca.us/Domain/2875,Claremont Middle School

http://www.ousd.k12.ca.us/Domain/314,Cleveland Elementary

http://www.ousd.k12.ca.us/Domain/2851,Coliseum College Prep Academy

http://www.ousd.k12.ca.us/Domain/1962,Community Day HS

http://www.ousd.k12.ca.us/Domain/850,Community United Elementary School

http://www.ousd.k12.ca.us/Domain/326,Crocker Highlands Elementary

http://www.ousd.k12.ca.us/Domain/1872,Dewey Academy

http://www.ousd.k12.ca.us/Domain/299,East Oakland Pride Elementary School

http://www.ousd.k12.ca.us/Domain/2239,East Oakland School of the Arts

http://www.ousd.k12.ca.us/Domain/2504,Edna M Brewer Middle School

http://www.ousd.k12.ca.us/Domain/2754,Elmhurst Community Prep

http://www.ousd.k12.ca.us/Domain/415,Emerson Elementary

http://www.ousd.k12.ca.us/Domain/352,EnCompass

http://www.ousd.k12.ca.us/Domain/891,Esperanza Academy

http://www.ousd.k12.ca.us/Domain/2801,Explore MS

http://www.ousd.k12.ca.us/Domain/1916,Far West

http://www.ousd.k12.ca.us/Domain/454,Franklin Elementary

http://www.ousd.k12.ca.us/Domain/2122,Fremont High School

http://www.ousd.k12.ca.us/Domain/2178,Freshman Prep Academy

http://www.ousd.k12.ca.us/Domain/2379,Frick Middle School

http://www.ousd.k12.ca.us/Domain/465,Fruitvale Elementary

http://www.ousd.k12.ca.us/Domain/697,Futures Elementary School

http://www.ousd.k12.ca.us/Domain/481,Garfield Elementary

http://www.ousd.k12.ca.us/Domain/532,Glenview Elementary

http://www.ousd.k12.ca.us/Domain/359,Global Family School

http://www.ousd.k12.ca.us/Domain/643,Grass Valley Elementary

http://www.ousd.k12.ca.us/Domain/337,Greenleaf Elementary

http://www.ousd.k12.ca.us/Domain/746,Hillcrest K-8

http://www.ousd.k12.ca.us/Domain/2375,Hillside Academy

http://www.ousd.k12.ca.us/Domain/924,Hoover Elementary

http://www.ousd.k12.ca.us/Domain/880,Horace Mann Elementary

http://www.ousd.k12.ca.us/Domain/710,Howard Elementary

http://www.ousd.k12.ca.us/Domain/866,International Comm. Elementary

http://www.ousd.k12.ca.us/Domain/913,Joaquin Miller Elementary

http://www.ousd.k12.ca.us/Domain/1296,Kaiser Elementary

http://www.ousd.k12.ca.us/Domain/902,Korematsu Discovery Acade

http://www.ousd.k12.ca.us/Domain/1192,La Escuelita Elementary

http://www.ousd.k12.ca.us/Domain/1508,Lafayette Elementary

http://www.ousd.k12.ca.us/Domain/1402,Lakeview Elementary

http://www.ousd.k12.ca.us/Domain/1254,Laurel Elementary

http://www.ousd.k12.ca.us/Domain/1080,Lazear Elementary

http://www.ousd.k12.ca.us/Domain/1426,Learning Without Limits

http://www.ousd.k12.ca.us/Domain/1979,Life Academy

http://www.ousd.k12.ca.us/Domain/1519,Lincoln Elementary School

http://www.ousd.k12.ca.us/Domain/1456,M L King Jr Elementary

http://www.ousd.k12.ca.us/Domain/2718,Madison Middle School

http://www.ousd.k12.ca.us/Domain/2091,Mandela High School

http://www.ousd.k12.ca.us/Domain/1415,Manzanita Community School

http://www.ousd.k12.ca.us/Domain/1351,Manzanita SEED

http://www.ousd.k12.ca.us/Domain/1388,Markham Elementary

http://www.ousd.k12.ca.us/Domain/1329,Marshall Elementary

http://www.ousd.k12.ca.us/Domain/1307,Maxwell Park Elementary

http://www.ousd.k12.ca.us/Domain/2263,McClymonds

http://www.ousd.k12.ca.us/Domain/1681,Melrose Leadership Academy

http://www.ousd.k12.ca.us/Domain/1994,MetWest

http://www.ousd.k12.ca.us/Domain/1285,Montclair Elementary

http://www.ousd.k12.ca.us/Domain/2515,Montera Middle School

http://www.ousd.k12.ca.us/Domain/1203,New Highland Academy

http://www.ousd.k12.ca.us/Domain/1687,Oakland High School

http://www.ousd.k12.ca.us/Domain/2308,OAKLAND INTERNATIONAL HIGH

http://www.ousd.k12.ca.us/Domain/1755,Oakland Technical High School

http://www.ousd.k12.ca.us/Domain/198,Oakland Unified School District

http://www.ousd.k12.ca.us/Domain/969,Oakland Unified School District

http://www.ousd.k12.ca.us/Domain/1683,Oakland Unified School District

http://www.ousd.k12.ca.us/Domain/2377,Oakland Unified School District

http://www.ousd.k12.ca.us/Domain/971,Parker Elementary

http://www.ousd.k12.ca.us/Domain/1012,Peralta Elementary

http://www.ousd.k12.ca.us/Domain/1023,Piedmont Avenue Elementary

http://www.ousd.k12.ca.us/Domain/1467,Place at Prescott

http://www.ousd.k12.ca.us/Domain/1628,REACH Academy

http://www.ousd.k12.ca.us/Domain/1049,Redwood Heights Elementary

http://www.ousd.k12.ca.us/Domain/1617,RISE

http://www.ousd.k12.ca.us/Domain/2080,Robeson Visual Performing Arts

http://www.ousd.k12.ca.us/Domain/2585,Roosevelt Middle School

http://www.ousd.k12.ca.us/Domain/2812,Roots International Academy

http://www.ousd.k12.ca.us/Domain/2274,Rudsdale Continuation

http://www.ousd.k12.ca.us/Domain/1589,Sankofa Academy

http://www.ousd.k12.ca.us/Domain/1143,OTX West Training Site

http://www.ousd.k12.ca.us/Domain/1154,Sequoia Elementary

http://www.ousd.k12.ca.us/Domain/1766,Skyline High School

http://www.ousd.k12.ca.us/Domain/1165,Madison Park Academy (TK-5)

http://www.ousd.k12.ca.us/Domain/1929,Sojourner Truth Independent Study

http://www.ousd.k12.ca.us/Domain/1901,Street Academy

http://www.ousd.k12.ca.us/Domain/2319,Student Website

http://www.ousd.k12.ca.us/Domain/1564,Think College Now

http://www.ousd.k12.ca.us/Domain/1181,Thornhill Elementary

http://www.ousd.k12.ca.us/Domain/2833,United for Success

http://www.ousd.k12.ca.us/Domain/2862,Urban Promise Academy

http://www.ousd.k12.ca.us/Domain/2430,West Oakland Middle School

http://www.ousd.k12.ca.us/Domain/2630,Westlake Middle School

http://www.ousd.k12.ca.us/Domain/1318,OUSD Career Pathways

http://www.ousd.k12.ca.us/Domain/878,ZZZ Additional Site

-J

**Comment by jgordon510** [comment]
I added a js file with a function that returns the schoolURLIndex.

**Comment by jgordon510** [comment]
I wrote a function that gets the proper URL from the array based on a school name.  The school names in the two datasets don't match exactly, but most of them do, and it's pretty quick to fix the index when they don't.

I also wrote a function that replaces the school names in the info-window with a link to the correct URL.  The only problem I'm having is figuring out where to call that function.  It needs to go in the callback of the tooltip window or something - it has to be called after the tooltip window is built.

**Pull request closed without merging**
